server:
  port: 8080
  max-http-header-size: 8192
spring:
  thymeleaf:
    prefix: classpath:/public/
    cache: true
  dubbo:
    appname: user-consumer
    registry: zookeeper://192.168.101.4:2181
    protocol: dubbo
  redis:
    port: 6379
    host: 192.168.101.4
    database: 0
    password: 123456
    pool:
      max-idle: 8
      max-wait: -1
      max-active: 8
      min-idle: 0
    timeout: 50000
  kafka:
    producer:
      bootstrap-servers: 192.168.101.4:9092
kafkaConfig:
  moduleName: user
wx:
  codeUrl: https://open.weixin.qq.com/connect/qrconnect
  appId: wx9168f76f000a0d4c
  redirectUri: http://localhost:8080/api/wx/callBack
  responseType: code
  scope: snsapi_login
  accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token
  secret: 8ba69d5639242c3bd3a69dffe84336c1
  grantType: authorization_code
  userInfoUrl: https://api.weixin.qq.com/sns/userinfo
  successUrl: http://localhost:82/api/index.html
