server:
  port: 84
spring:
  thymeleaf:
    prefix: classpath:/public/
    cache: true
  dubbo:
    appname: pay-consumer
    registry: zookeeper://192.168.101.4:2181
    protocol: dubbo
  redis:
    port: 6379
    host: 192.168.101.4
    database: 0
    password: 123456
    pool:
      max-idle: 8
      max-wait: -1
      max-active: 8
      min-idle: 0
    timeout: 5000
  kafka:
    producer:
      bootstrap-servers: 192.168.101.4:9092
  activemq:
    broker-url: tcp://192.168.101.4:61616
    in-memory: true
    pool:
      enabled: false
    packages:
      trust-all: true
kafkaConfig:
  moduleName: pay
alipay-config:
  APPID: 2021000118618673
  PRIVATEKEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCevnszLeZhMRrtd3Eny9v1PM+3shqWUWormDDKD6Ilc7AtyWAfM1zLSSdeLEmIMhvUSOh3DgvdMfI5eE3c6nqHvBhyxI/9jsxhLaI5VUof9xcKuLz2jnjRfx/tT9t2sCWNnI6rnM8czbzEyQvNFTqhEooD7aJ03ZwHYZb12pVPuoGws3F3vFefUEjCmV/Nvr4iQeD9bi8pGh1G+15IGE49LUIvAc+UapjDEdelL6cCyT0e1yEoeXMZi6vIgbuyrv+ZJIadTsaUUKp9J6AfOZXDy0tCUKYjavUSYVIidr6e407kOT66plu0Twma/HJrQ+JJmYixKJidhA75kNoPUOuXAgMBAAECggEAZevq8htAVZrPrTQJJQIQwc4/l7P0uhqfzkmy2alb9CvpLBylaKLzq1nWuvI4bAewMoZ1KyuLloOhACEr7PFnpoqwL8/gm23571L7W1BVfVyKIMooGS20iN3UQ+wH/pZuJhQkzi6qE9ZMoxRqTUyaDhz3HDqRGfPHYD3aTRQA1eTn0RhpRZ4FxB/oKYnzrFd0qbDJY3C++lj3ashgg6JIPvA+kQ+S1muQCJwIOIkYV9kXVMKJolyYmwa8J60PMElQJLTITA5AMubfv+LeuwS1iSK60MHSdpDSminVqdCXOXp9t3P/MJCxNrYbWerTxpliJiLSBq0DYBfNVllxZU5TUQKBgQDcAK3wEoYhkHcLTUdPZliSHKq5nz3DqU0QJZBmX6JKR6iylqZppsWOFgftW1Vt+5ouw5uzrSHP0xDEKHZrtBI9JFoc6Lhp+dFro/V/vsSMb7yE2OaBFSgbq0bERchNfufGrKmBl5Go5085LYtymaYbq6AkaE06rEUQapGF5+aHzQKBgQC4t9gUnUYCQimbbyaX0YU+G8adNmMe9OSPoe+s8RItwq1sdWK8aukbJnMNgtOcOh87DMZCwUHvw9AxxhLW0ZNy1Fn//FzB5//6SjtMG9urS8HyhgFY+UOC6E/QYs5v5UMYpmy9dk9TGqJs4ccEEaL6qXqmbqf7UKKUatFJemoU8wKBgFgEvZJLFvbewYH4DQurOsxaQ8O3/hIF7hsDrF4I7Pki6k9pDnM+kdNi5REFdYxnGSyUffrIzbpEC3UvaxF0Hcfwf00Jnp5noG2cT2AohqJZIedUkAQc3ssTH2DvOlAm8bv+4GJErbYRtRR/MEdNSbPQWmW2hQ9wVMFYoZgdS5IRAoGAE9HmJZAaivN+c2chxPh+S4O/c+76A8BTJfZCOVRElxRkd1bBGWZ/TKJ7hd+bxQ+XekaMn20NHiTsmeqe6t3h7FhMr+LsMQIrvTdp1WjH0UF3tgYa7ukQDWPP7JQtgmQfJu30jP+80zXwZ65yJEWgLzUwK9uDuruUNkif3Dp+V3ECgYEApksP+yl0vdmjH9/Qr50zFN/Ps/XctMG9Vc2rXeMckWacrSm1LtgdD2gOKs2iZi1CFMe9LzdOvzauTzMPi6c6pU5Aq82ihaYPwB0fnCfOxjY4Vo08Naga+MLUBUv4DvUUDjmuDr7LbogD+6F73BsHo/w8RojEfGE+XGCjvh2GjIM=
  ALIPAYPUBLICKEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjrL4Oq+yCDnq0Tr7G8F9hjOcfUoAnj40suKO90XnqKOwO2OpCDH5VDgdFau26YlVheTHMC1BzJekorxJ6WpAHHgWPGo82ovUtKL8zWi+h60GST8Ow8r3Vjn9Q1lU1Mev9Qlto1F4OQIoy3NVN9Lk4s/4caFNpw1I35qkUX3Se1NndfWS8lgn70Td41bkrr0oLlyWs/d++6YqAMpGExdHJ6BEz8vTgI22+6so5PruYJTeCvth69tUvB3rRX9i4LeYfYCPdxb9ktZzP6q9zXEVsclTRnWBBLEbcqt/hH1+oDTnu185hk/wzvCjWJaaWYy/UPwgWy7768tktg6pJeOi1wIDAQAB
  notify_url: http://wyo9w7q4h33t.ngrok2.xiaomiqiu.cn/api/payNotify
  return_url: http://wyo9w7q4h33t.ngrok2.xiaomiqiu.cn/api/callBack
  CHARSET: UTF-8
  FORMAT: json
  URL: https://openapi.alipaydev.com/gateway.do
  SIGNTYPE: RSA2
  paySuccessUrl: http://192.168.101.4:84/api/paySuccess.html
  payFailUrl: http://192.168.101.4:84/payFail.html

wxPayConfig:
  appID: wxab8acb865bb1637e
  mchID: 11473623
  key: 2ab9071b06b9f739b950ddb41db2690d
  notifyUrl: http://wyo9w7q4h33t.ngrok2.xiaomiqiu.cn/api/wxPayNotify

