spring:
  redis:
    database: 1
    host: 192.168.101.4
    port: 6379
    user: root
    password: 123456
    timeout: 6000
  activemq:
    broker-url: tcp://192.168.101.4:61616?jms.optimizeAcknowledge=true&jms.optimizeAcknowledgeTimeOut=30000&jms.redeliveryPolicy.maximumRedeliveries=10
    user: admin
    password: admin
    packages:
      trust-all: true
---
spring:
  profiles: dev1
server:
  port: 8881
---
spring:
  profiles: dev2
server:
  port: 8882

