server:
  port: 83
  max-http-header-size: 8192
spring:
  thymeleaf:
    prefix: classpath:/public/
    cache: true
  dubbo:
    appname: order-consumer
    registry: zookeeper://192.168.101.4:2181
    protocol: dubbo
  redis:
    port: 6379
    host: 192.168.101.4
    database: 0
    password: 123456
    pool:
      max-idle: 8
      max-wait: -1
      max-active: 8
      min-idle: 0
    timeout: 50000
  activemq:
    broker-url: tcp://192.168.101.4:61616
    user: admin
    password: admin
    packages:
      trust-all: true
    in-memory: true
    pool:
      enabled: false
  kafka:
    producer:
      bootstrap-servers: 192.168.101.4:9092
kafkaConfig:
  moduleName: order


